### ISSUE TITLE
Grants: 23-H2 :: ACTUS Foundation

### ISSUE THREAD

**Issue by ghost** [cspr-rad/grants#4]
Further support for ACTUS Foundation activities.
- Links
  - [Foundation Website](https://www.actusfrf.org)

**Comment by ghost** [comment]
### Towards 2.0 Specification

Current version of specification, i.e. v1.1, is sub-optimal in several respects.  Discrepancies exist and formal notation needs to be improved.  Grant money could be spent on ensuring better coordination in taking steps towards v2.0.

**Comment by ghost** [comment]
### Educational Materials

Grant money could be spent on extending the range of available multimedia pedagogic materials.  Such materials should be packaged in such a way so as to be easily transmissible over social media channels such as TikTok. 

It would be interesting to use an animation studio, e.g. a dancing taxonomy (see @NorfairKing for further info).

**Comment by ghost** [comment]
Email has been sent to Allan Mendelowitz requesting an invoice.

**Comment by ghost** [comment]
[Invoice for payment](https://github.com/cspr-rad/grants/files/12803130/ACTUS.Financial.Research.Foundation.-.Invoice.2318.for.Casper.Association.Support.for.ACTUS.2023.pdf) has been sent to billing.

**Comment by JHallager** [comment]
Invoice has been settled
